databases:
  - name: school_db
    databaseName: school_management
    user: school_user

services:
  - type: web
    name: school-management-system
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn workplace_system.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: school_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: school-management-system-vipe.onrender.com,.onrender.com,localhost
      - key: EMAIL_BACKEND
        value: django.core.mail.backends.smtp.EmailBackend
      - key: EMAIL_HOST
        value: mail.privateemail.com
      - key: EMAIL_PORT
        value: 465
      - key: EMAIL_USE_SSL
        value: True
      - key: EMAIL_USE_TLS
        value: False
      - key: EMAIL_HOST_USER
        value: cranictech@elincorporatedlimited.com
      - key: EMAIL_HOST_PASSWORD
        value: Happylife227.#
      - key: DEFAULT_FROM_EMAIL
        value: cranictech@elincorporatedlimited.com
