databases:
  - name: school_db
    databaseName: school_management
    user: school_user

services:
  - type: web
    name: school-management-system
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn workplace_system.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: school_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        sync: false
